### ISSUE TITLE
Some runners get two runs attributed per year

### ISSUE THREAD

**Issue by panmari** [misch/gpCollect#13]
This _should_ not happen afaik? I. e. the query is crafted in a way that should prevent this. Nevertheless, we have 9 participations for 

Markus Zimmermann Bern

With multiple participations per year.

**Comment by misch** [comment]
The join was not the correct thing to do, as it would only exclude e.g. [runner1 , critical_run_day] but not [runner1 , non-critical_run_day] - therefore, runner1 would still be in the list of possible matches, if he ran on only one non-critical run_day (no matter if he participated also on the critical run_day or not).

However, the merging is still quite random e.g. in the discussed case of Markus Zimmermann from Bern. It just depends on the order of the data in the parsed file.
