### ISSUE TITLE
Treat missing values in chart

### ISSUE THREAD

**Issue by panmari** [misch/gpCollect#24]
How should missing runs be treated in the chart? By default, highcharts interpolates between the years, making it seem like there is somehow a data point in the middle. 

An alternative I implemented recently is to 'stop' the graph if there is a value missing, then restart it from the next year present. Here in images:
![selection_044](https://cloud.githubusercontent.com/assets/719020/9606920/70e67ef4-50c6-11e5-9bef-ae18a989a106.png)
vs
![selection_043](https://cloud.githubusercontent.com/assets/719020/9606912/6cc14e3a-50c6-11e5-9729-fe56127fc7b1.png)
(difference here is the green line, that is not connected in the second case).

**Comment by panmari** [comment]
The behavior of the second graphic is implemented on the branch not_connect_if_missing. What's your opinion @misch ?

**Comment by misch** [comment]
I definitely like the new look! :+1:

**Comment by misch** [comment]
I merged it. :) 'Cause it's great ^^

**Comment by panmari** [comment]
Code there might need some more cleanup, though XD. Coding exercise: Do you spot any issues with this code? Try to run it locally (just go on a show page of a runner) and check the log.

**Comment by misch** [comment]
Hm with 7ba3ec7 we now arrived from
![before](https://cloud.githubusercontent.com/assets/461605/9655471/7453be00-5231-11e5-907a-07b7cebb0d24.png)

at...
![after](https://cloud.githubusercontent.com/assets/461605/9655476/7d60e8c4-5231-11e5-9995-08dba10313c8.png)

... Actually it should also be possible to do the averaging with a group by:
SELECT runner_id, avg(duration) FROM runs WHERE runner_id IN (...) GROUP BY runner_id

I'm a bit clueless though where to do that...

**Comment by panmari** [comment]
merged your fix @misch

**Comment by panmari** [comment]
I refactored chart for dealing with the remaining issues, I'll do a PR as soon as I get an answer to my other PR #26
