### ISSUE TITLE
New Feature: allow users to make a 'MergeRunnersRequest'

### ISSUE THREAD

**Issue by panmari** [misch/gpCollect#25]
There is no way we can detect all duplications by (more or less) smart analysis of data. Therefore, it would be beneficial to add some feature to allow merging by user input. 

In my opinion, it would be best if the merge is only executed for the user that requested it, then upon inspection by an admin (or some machine based validation) it can be accepted or rejected for the whole userbase. 

PS: This would be our first really 'railsy' feature, since it really should allow user to create DB entries.

**Comment by misch** [comment]
I thought about something like that as well... Also, we might have merged runs that do not truly belong to the same person (as we just created more Runners with same names and distributed the Runs to them in whatever order they came in the scraped data), and we might have made errors in our assumptions about accents, umlaute, case and spacing. So, I agree that it should be editable in some way.

What do you mean by "merge is only executed for the user that requested it?" - are we planning to make users?

**Comment by panmari** [comment]
Well, a user is anyone that clicks around on your website. I don't think we should make a login/database model for users.

I think we are still quite conservative with our merges. I'd say that the number of unmerged runners is much much higher than the wrongly merged ones. Or in more scientific terms: I expect our precision to be way higher than our recall ([precision and recall](https://en.wikipedia.org/wiki/Precision_and_recall))

**Comment by misch** [comment]
Let's first tackle the unmerged ones...

We could make something like this:
![merge_request](https://cloud.githubusercontent.com/assets/461605/9653544/56a9c3d4-5224-11e5-8d0b-f697fc95136d.jpg)

[And e.g. later add a "merge Runners" button to the sidebar (where the remembered Runners are then pre-selected in the merge request or so)]

**Comment by misch** [comment]
"change Runner" would be this little blue link where one could switch the Runner that will stay (others will be merged to it)... And then maybe a "send merge request" button or so might help as well :P

**Comment by panmari** [comment]
It's a bit strange, to have all functionalities in the sidepanel, but that's how I implemented it right now XD.
![selection_046](https://cloud.githubusercontent.com/assets/719020/9653603/d5e686b4-5224-11e5-9324-841ed2688ff3.png)

**Comment by panmari** [comment]
When clicking on 'merge remembered runners', youre taken to this screen:
![selection_047](https://cloud.githubusercontent.com/assets/719020/9653637/1888fede-5225-11e5-8228-8098e35182d0.png)
What would be sensible defaults for the merged runner? Just the data from the runner with the most recent run?

**Comment by misch** [comment]
Why are you so fast :'( I did not even figure out yet where to add anything to make a cool example. :( Anyway, looks good! I would really not do anything too complicated - either the most current data or simply the first one of the selected.

**Comment by misch** [comment]
(or give the user the possibility to select whatever Runner as the "main")

**Comment by panmari** [comment]
> either the most current data or simply the first one of the selected.

That's a bit of a problem right now. There is no real order in the 'remembered' list. They are sorted by DB-id, which does not mean much. This is a HUGE todo

> (or give the user the possibility to select whatever Runner as the "main")

That would be a good alternative to full control over what's entered. Maybe we should come back to this if there's a lot of abuse? For now I'd prefer the approach of giving the user full control over the data (maybe with some server side validation). Are you ok with that?

**Comment by misch** [comment]
We just don't have anything that we can assume is more valid than the other - except maybe if one user has more non-empty attributes than another (but that's in many cases [e.g. changing hometown] not helping too much)...

If you don't feel comfortable with taking the first/last by db-id, then how about use a random number to select whatever db-id :P

No, seriously. Maybe the number of attributes could be a start?

**Comment by misch** [comment]
> For now I'd prefer the approach of giving the user full control over the data (maybe with some server side validation). Are you ok with that?

We could combine it - that e.g. clicking on a user automatically fills the boxes with the text from the given user...?

**Comment by panmari** [comment]
> We just don't have anything that we can assume is more valid than the other - except maybe if one user has more non-empty attributes than another (but that's in many cases [e.g. changing hometown] not helping too much)...

Right, but already a blank check would be great. We could further e. g. check the levenstein distance of every attribute with the new merged attributes and make some threshold on that.

> If you don't feel comfortable with taking the first/last by db-id, then how about use a random number to select whatever db-id :P

I think there is a missunderstanding there, I'll elaborate the problem after lunch.

**Comment by panmari** [comment]
> We could combine it - that e.g. clicking on a user automatically fills the boxes with the text from the given user...?

That's how I implemented it on my branch. 

The other decision we have to take is if we really delete the merged runners or if we 'soft-delete' them, meaning that we set some flag 'deleted = true' and exclude them from all queries.

**Comment by panmari** [comment]
For now, we go with the 'full delete merged runners' approach, since merge requests can only be accepted by admins, we hopefully will never want to revert a merge. This has the advantage that our queries stay simple.
